name: Portal Integration Testing - Generic
on:
  workflow_call:
    inputs:
      environment:
        description: 'Specifies the GitHub deployment environment.'
        required: true
        type: string
permissions:
    id-token: write
    contents: read

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENV: ${{ vars.ENV }}

    steps:
    - name: Print environment variables
      run: |
        echo "vars Environment: ${{ vars.ENV }}"
        echo "GH Environment: ${{ inputs.environment }}"
        echo "github.ref: ${{ github.ref_name }}"
