name: Portal Integration Testing - DEV
on:
  push:
    branches:
      - main
      - AM-1
    
permissions:
    id-token: write
    contents: read

jobs:
  integration-tests-dev:
    if: github.ref != 'refs/heads/main'
    name: Run Integration Tests dev
    runs-on: ubuntu-latest
    environment: dev
    env:
      ENV: ${{ vars.ENV }}

    steps:
    - name: Print environment variables
      run: |
        echo "Environment: ${{ vars.ENV }}"

  integration-tests-prod:
    if: github.ref == 'refs/heads/main'
    name: Run Integration Tests prod
    runs-on: ubuntu-latest
    environment: prod
    env:
      ENV: ${{ vars.ENV }}

    steps:
    - name: Print environment variables
      run: |
        echo "Environment: ${{ vars.ENV }}"
