name: Portal Integration Testing - DEV
on:
  push:
    branches:
      - main        
    
permissions:
    id-token: write
    contents: read

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    environment: production
    env:
      ENV: ${{ vars.ENV }}

    steps:
    - name: Print environment variables
      run: |
        echo "Environment: ${{ vars.ENV }}"
