name: Portal Integration Testing
on:
  push:
    
permissions:
    id-token: write
    contents: read

jobs:
  integration-tests-dev:
    name: Run Integration Tests DEV
    uses: alcantar28/GHAReusableWorkflows/.github/workflows/integration_testing_generic.yml@main
    with:
      environment: dev

  integration-tests-stage:
    name: Run Integration Tests STAGE
    uses: alcantar28/GHAReusableWorkflows/.github/workflows/integration_testing_generic.yml@main
    with:
      environment: stage

  integration-tests-prod:
    name: Run Integration Tests PROD
    uses: alcantar28/GHAReusableWorkflows/.github/workflows/integration_testing_generic.yml@main
    with:
      environment: prod
